version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
      - image: radarrelayinc/0x-testrpc:latest
    steps:
      - checkout
      # - run:
      #     name: Install sonarscanner
      #     command: 'sudo npm install -g sonarqube-scanner'
      # - run:
      #     name: Ensure sonar-scanner installed
      #     command: sonar-scanner --help || sleep 2 && sonar-scanner --help || sleep 2 && sonar-scanner --help
      - run:
          name: Install libusb
          command: sudo apt install libusb-1.0-0-dev
      - run:
          name: Install typescript
          command: 'sudo npm install -g typescript'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
      # - run:
      #     name: Push test results
      #     command: './runSonarCloudAnalysis.sh'
